version: '3.6'

services:

#================================================================================================
# PORTAINER
#================================================================================================
  portainer:
    restart: always
    build:
      context: .
    ports:
      - "8118:9000"
    volumes:
      #- /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DATA_PORTAINER:-/opt/data/docker/portainer2.6}:/data
    environment:
      - PORTAINER_VERSION=2.6.3
      - PORTAINER_HOME=/var/lib/portainer
    privileged: true
    tty: true
